Repository UQcsse3200/2025-studio-4, pull requests merged in 2025-09, with the labels that each got.

#54 New currency types
  source/core/assets/sounds/metal_scrap_currency_collect.ogg
  source/core/assets/sounds/neurochip_currency_collect.ogg
  source/core/assets/sounds/titanium_core_currency_collect.ogg
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/components/currencysystem/CollectibleComponent.java
  source/core/src/main/com/csse3200/game/components/currencysystem/CurrencyComponent.java
  source/core/src/main/com/csse3200/game/components/currencysystem/CurrencyManagerComponent.java
  source/core/src/main/com/csse3200/game/components/player/PlayerStatsDisplay.java
  source/core/src/test/com/csse3200/game/components/currencysystem/CurrencyManagerComponentTest.java
Labels: sprint 2

#79 Update CurrencyFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/CurrencyFactory.java
Labels: sprint 2, team 5

#104 Team 6 homepage
  CutsceneSystemVerification.java
  saves/game_save.json
  source/core/assets/images/Game_Victory.png
  source/core/assets/images/Opening_Cutscene_Screen.png
  source/core/assets/images/logo.png
  source/core/assets/saves/game_save.json
  source/core/src/main/com/csse3200/game/GdxGame.java
  source/core/src/main/com/csse3200/game/areas/MapEditor.java
  source/core/src/main/com/csse3200/game/components/PlayerCombatStatsComponent.java
  source/core/src/main/com/csse3200/game/components/audio/BackgroundMusicComponent.java
  source/core/src/main/com/csse3200/game/components/audio/SoundEffectComponent.java
  source/core/src/main/com/csse3200/game/components/enemy/EnemyTypeComponent.java
  source/core/src/main/com/csse3200/game/components/hero/HeroOneShotFormSwitchComponent.java
  source/core/src/main/com/csse3200/game/components/maingame/MainGameActions.java
  source/core/src/main/com/csse3200/game/components/maingame/MainGameOver.java
  source/core/src/main/com/csse3200/game/components/maingame/MainGameWin.java
  source/core/src/main/com/csse3200/game/components/maingame/PauseMenuDisplay.java
  source/core/src/main/com/csse3200/game/components/maingame/SaveMenuDisplay.java
  source/core/src/main/com/csse3200/game/components/mainmenu/MainMenuActions.java
  source/core/src/main/com/csse3200/game/components/mainmenu/MapSelectionActions.java
  source/core/src/main/com/csse3200/game/components/mainmenu/MapSelectionDisplay.java
  source/core/src/main/com/csse3200/game/components/settingsmenu/SettingsMenuDisplay.java
  source/core/src/main/com/csse3200/game/entities/factories/BossEnemyFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/DividerChildEnemyFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/DroneEnemyFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/GruntEnemyFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/TankEnemyFactory.java
  source/core/src/main/com/csse3200/game/files/UserSettings.java
  source/core/src/main/com/csse3200/game/screens/GameOverScreen.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
  source/core/src/main/com/csse3200/game/screens/MainMenuScreen.java
  source/core/src/main/com/csse3200/game/screens/MapSelectionScreen.java
  source/core/src/main/com/csse3200/game/screens/OpeningCutsceneScreen.java
  source/core/src/main/com/csse3200/game/screens/SaveSelectionScreen.java
  source/core/src/main/com/csse3200/game/screens/SettingsScreen.java
  source/core/src/main/com/csse3200/game/screens/VictoryScreen.java
  source/core/src/main/com/csse3200/game/services/AudioService.java
  source/core/src/main/com/csse3200/game/services/SaveGameService.java
  source/core/src/main/com/csse3200/game/services/ServiceLocator.java
  source/core/src/test/com/csse3200/game/components/audio/BackgroundMusicComponentTest.java
  source/core/src/test/com/csse3200/game/components/audio/SoundEffectComponentTest.java
  source/core/src/test/com/csse3200/game/components/maingame/MainGameActionsSaveFlowTest.java
  source/core/src/test/com/csse3200/game/components/mainmenu/MapSelectionScreenSmokeTest.java
  source/core/src/test/com/csse3200/game/files/UserSettingsPersistenceTest.java
  source/core/src/test/com/csse3200/game/integration/AudioIntegrationTest.java
  source/core/src/test/com/csse3200/game/screens/GameOverScreenTest.java
  source/core/src/test/com/csse3200/game/screens/OpeningCutsceneScreenTest.java
  source/core/src/test/com/csse3200/game/screens/VictoryScreenTest.java
  source/core/src/test/com/csse3200/game/services/AudioServiceTest.java
  source/core/src/test/com/csse3200/game/services/ServiceLocatorTest.java
  t
  tatus
Labels: sprint 2, team 6
